import { NoteData } from "types/types";

export function renderEntityNote(params: {
  summary: string;
  interpretation: string;
  connections: string[];
  emotions: string[];
  notes: NoteData[];
}) {
  const {
    summary,
    interpretation,
    connections,
    emotions,
    notes
  } = params;

  const sourceLinks = notes.map(n => `- [[${n.file.path}]]`).join("\n");

  const emotionTags = (emotions || []).map(e =>
    `#emotion/${e.toLowerCase().replace(/\s+/g, "_")}`
  );
  const tags = [`#luma/`, ...emotionTags, `#dream-symbol`].join(" ");

  return `
**Recurring Emotions:** ${emotions?.join(", ") || "None"}  
**Appears In:**  
${sourceLinks}

---

## 🔍 Overview

> ${summary}

---

## 🔗 Connections

${connections?.map(c => `- Related to [[${c}]]`).join("\n") || "- No connections detected."}

---

## 🧠 Interpretation

_autogenerated by Luma_  
${interpretation}

---

## 🧬 Tags

${tags}
`;
}
